### ISSUE TITLE
Don't link to the abandoned blog

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy.github.com#107]
I notice sympy.org links to http://sympy.blogspot.com/ "Official SymPy blog". The last post there is from 2013. Given that release notices are posted on sympy.org itself, and blogs get little attention in post-Google-Reader era, I think that particular link should be dropped. All it does is make SymPy look more like abandonware.

**Comment by asmeurer** [comment]
Agreed (I still do have access to the blog, by the way).
