### ISSUE TITLE
The series() is beautiful but has something wrong

### ISSUE THREAD

**Issue by intmeX** [sympy/sympy.github.com#140]
## The wrong case is 
![sympy](https://user-images.githubusercontent.com/57341820/85302786-2d0f3e80-b4dc-11ea-97f4-fe529f3c7a61.png)

I think the prefix “x” is lacked in the result. But I still has some possibility to make it wrong.
Oh, in any case, the sympy is great. I'm the 100th star!

**Comment by jksuom** [comment]
Actually, `x` is not lacking, it only comes last before the order term. If you want to get a nice expansion in powers of `x`, use `series(ln(1 + x), x, 0, 10)`.

**Comment by intmeX** [comment]
OO yes，I ignored it. Thank you~
