### ISSUE TITLE
Tutorial uses deprecated code

### ISSUE THREAD

**Issue by leftishness** [sympy/sympy.github.com#150]
I'm attempting to follow this: https://docs.sympy.org/latest/tutorial/calculus.html

I'm using Python 3.8.5 and SymPy 1.6.2 and everything fails.

**Comment by oscarbenjamin** [comment]
Can you be more specific than "everything fails"?

How are you running the examples?

**Comment by leftishness** [comment]
``C, including its class ClassRegistry, has been deprecated since SymPy
1.0. It will be last supported in SymPy version 1.0. Use direct
imports from the defining module instead. See
https://github.com/sympy/sympy/issues/9371 for more info.
  SymPyDeprecationWarning(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.core.add with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.core.add instead. See
https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.tensor.array with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.tensor.array instead. See
https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.core.basic with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.core.basic instead. See
https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.solvers.bivariate with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.solvers.bivariate
instead. See https://github.com/sympy/sympy/issues/18245 for more
info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.logic.boolalg with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.logic.boolalg instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.core.cache with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.core.cache instead. See
https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.matrices.common with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.matrices.common instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.core.compatibility with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.core.compatibility
instead. See https://github.com/sympy/sympy/issues/18245 for more
info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.sets.conditionset with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.sets.conditionset
instead. See https://github.com/sympy/sympy/issues/18245 for more
info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.core.containers with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.core.containers instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.sets.contains with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.sets.contains instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.discrete.convolutions with 'from sympy import *' has
been deprecated since SymPy 1.6. Use import
sympy.discrete.convolutions instead. See
https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.core.coreerrors with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.core.coreerrors instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.simplify.cse_main with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.simplify.cse_main
instead. See https://github.com/sympy/sympy/issues/18245 for more
info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.simplify.cse_opts with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.simplify.cse_opts
instead. See https://github.com/sympy/sympy/issues/18245 for more
info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.geometry.curve with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.geometry.curve instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.core.decorators with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.core.decorators instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.matrices.dense with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.matrices.dense instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.solvers.deutils with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.solvers.deutils instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.geometry.ellipse with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.geometry.ellipse instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.geometry.entity with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.geometry.entity instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.simplify.epathtools with 'from sympy import *' has
been deprecated since SymPy 1.6. Use import sympy.simplify.epathtools
instead. See https://github.com/sympy/sympy/issues/18245 for more
info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.geometry.exceptions with 'from sympy import *' has
been deprecated since SymPy 1.6. Use import sympy.geometry.exceptions
instead. See https://github.com/sympy/sympy/issues/18245 for more
info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.core.expr with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.core.expr instead. See
https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.concrete.expr_with_intlimits with 'from sympy import
*' has been deprecated since SymPy 1.6. Use import
sympy.concrete.expr_with_intlimits instead. See
https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.concrete.expr_with_limits with 'from sympy import *'
has been deprecated since SymPy 1.6. Use import
sympy.concrete.expr_with_limits instead. See
https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.matrices.expressions with 'from sympy import *' has
been deprecated since SymPy 1.6. Use import sympy.matrices.expressions
instead. See https://github.com/sympy/sympy/issues/18245 for more
info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.core.exprtools with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.core.exprtools instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.ntheory.factor_ with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.ntheory.factor_ instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.core.facts with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.core.facts instead. See
https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.sets.fancysets with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.sets.fancysets instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.core.function with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.core.function instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.ntheory.generate with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.ntheory.generate instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.concrete.gosper with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.concrete.gosper instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.matrices.immutable with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.matrices.immutable
instead. See https://github.com/sympy/sympy/issues/18245 for more
info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.tensor.index_methods with 'from sympy import *' has
been deprecated since SymPy 1.6. Use import sympy.tensor.index_methods
instead. See https://github.com/sympy/sympy/issues/18245 for more
info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.tensor.indexed with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.tensor.indexed instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.solvers.inequalities with 'from sympy import *' has
been deprecated since SymPy 1.6. Use import sympy.solvers.inequalities
instead. See https://github.com/sympy/sympy/issues/18245 for more
info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.logic.inference with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.logic.inference instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.integrals.integrals with 'from sympy import *' has
been deprecated since SymPy 1.6. Use import sympy.integrals.integrals
instead. See https://github.com/sympy/sympy/issues/18245 for more
info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.geometry.line with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.geometry.line instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.core.logic with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.core.logic instead. See
https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.integrals.manualintegrate with 'from sympy import *'
has been deprecated since SymPy 1.6. Use import
sympy.integrals.manualintegrate instead. See
https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.matrices.matrices with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.matrices.matrices
instead. See https://github.com/sympy/sympy/issues/18245 for more
info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.integrals.meijerint with 'from sympy import *' has
been deprecated since SymPy 1.6. Use import sympy.integrals.meijerint
instead. See https://github.com/sympy/sympy/issues/18245 for more
info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.core.mod with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.core.mod instead. See
https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.core.mul with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.core.mul instead. See
https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.core.multidimensional with 'from sympy import *' has
been deprecated since SymPy 1.6. Use import
sympy.core.multidimensional instead. See
https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.ntheory.multinomial with 'from sympy import *' has
been deprecated since SymPy 1.6. Use import sympy.ntheory.multinomial
instead. See https://github.com/sympy/sympy/issues/18245 for more
info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.core.numbers with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.core.numbers instead. See
https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.solvers.ode with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.solvers.ode instead. See
https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.core.operations with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.core.operations instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.sets.ordinals with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.sets.ordinals instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.geometry.parabola with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.geometry.parabola
instead. See https://github.com/sympy/sympy/issues/18245 for more
info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.ntheory.partitions_ with 'from sympy import *' has
been deprecated since SymPy 1.6. Use import sympy.ntheory.partitions_
instead. See https://github.com/sympy/sympy/issues/18245 for more
info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.solvers.pde with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.solvers.pde instead. See
https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.geometry.plane with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.geometry.plane instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.geometry.point with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.geometry.point instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.geometry.polygon with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.geometry.polygon instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.solvers.polysys with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.solvers.polysys instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.core.power with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.core.power instead. See
https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.sets.powerset with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.sets.powerset instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.ntheory.primetest with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.ntheory.primetest
instead. See https://github.com/sympy/sympy/issues/18245 for more
info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.concrete.products with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.concrete.products
instead. See https://github.com/sympy/sympy/issues/18245 for more
info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.solvers.recurr with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.solvers.recurr instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.core.relational with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.core.relational instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.ntheory.residue_ntheory with 'from sympy import *' has
been deprecated since SymPy 1.6. Use import
sympy.ntheory.residue_ntheory instead. See
https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.core.rules with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.core.rules instead. See
https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.sets.sets with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.sets.sets instead. See
https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.core.singleton with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.core.singleton instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.integrals.singularityfunctions with 'from sympy import
*' has been deprecated since SymPy 1.6. Use import
sympy.integrals.singularityfunctions instead. See
https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.solvers.solvers with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.solvers.solvers instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.matrices.sparse with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.matrices.sparse instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.matrices.sparsetools with 'from sympy import *' has
been deprecated since SymPy 1.6. Use import sympy.matrices.sparsetools
instead. See https://github.com/sympy/sympy/issues/18245 for more
info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.concrete.summations with 'from sympy import *' has
been deprecated since SymPy 1.6. Use import sympy.concrete.summations
instead. See https://github.com/sympy/sympy/issues/18245 for more
info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.core.symbol with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.core.symbol instead. See
https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.integrals.transforms with 'from sympy import *' has
been deprecated since SymPy 1.6. Use import sympy.integrals.transforms
instead. See https://github.com/sympy/sympy/issues/18245 for more
info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.simplify.traversaltools with 'from sympy import *' has
been deprecated since SymPy 1.6. Use import
sympy.simplify.traversaltools instead. See
https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.integrals.trigonometry with 'from sympy import *' has
been deprecated since SymPy 1.6. Use import
sympy.integrals.trigonometry instead. See
https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(
/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning: 
importing sympy.geometry.util with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.geometry.util instead.
See https://github.com/sympy/sympy/issues/18245 for more info.
  self.Warn(``

**Comment by asmeurer** [comment]
This is the issue tracker for the SymPy website. If you are still seeing this issue with the latest version of SymPy, please open an issue in the SymPy issue tracker.
