### ISSUE TITLE
Latex printing exponentiated symbols with superscripts fails

### ISSUE THREAD

**Issue by mfranckie** [sympy/sympy.github.com#152]
When defining a symbol which contains a superscript in the name, such as a complex conjugated or adjoint conjugated variable, latex printing the exponent of it does not automatically surround it with parentheses. For example:

from sympy import Symbol
ad = Symbol('a^\\ast')
ad*ad

>>> a^\ast^{2}

I do not understand how to fix this, without defining the symbol to always have parentheses.

**Comment by sylee957** [comment]
This is not an issue in the latest version I think
