### ISSUE TITLE
Integration is wrong

### ISSUE THREAD

**Issue by GoldenMan123** [sympy/sympy.github.com#157]
Hello!

Recently I've found that interation of function f = (sqrt(1 + x * sin(x)) - 1) / (exp(x ** 2) - 1) on (0, 1) results in -pi/2 but the correct answer is pi/2. This function is positive on that interval.

Also I can see that sympy.plotting.plot(sympy.diff(sympy.integrate(f))) and sympy.plotting.plot(f) visually differ by a sign.

Wolfram Alpha: https://www.wolframalpha.com/input/?i=integrate+1+%2F+%28%282+-+x%29+*+sqrt%281+-+x%29%29+from+0+to+1

**Comment by GoldenMan123** [comment]
SymPy version: 1.7.1

[
![Screenshot from 2021-03-13 22-02-20](https://user-images.githubusercontent.com/7023578/111041134-d2da5300-8447-11eb-83dc-75464a1a467f.png)
](url)

**Comment by RajMukherjee1601** [comment]
good morning sir ,I can solve this problem can u assign me this problem ??

**Comment by RajMukherjee1601** [comment]
Just need to change the value 0 in place of 1 and 1 in place of 0

**Comment by RajMukherjee1601** [comment]
![image](https://user-images.githubusercontent.com/87653848/159636835-676b8e75-2a1d-48c1-a7d8-a9cf4b733a78.png)

**Comment by oscarbenjamin** [comment]
This issue should be opened on the sympy repo. This repo is for the website.
