### ISSUE TITLE
Integration is NOT correct!

### ISSUE THREAD

**Issue by weishanlee** [sympy/sympy.github.com#161]
![圖片1](https://user-images.githubusercontent.com/44011158/126897533-1aa3c024-1fe0-4923-83ef-eab344d1efe9.jpg)

The answer should be π/12

**Comment by certik** [comment]
@weishanlee can you please report it here: https://github.com/sympy/sympy? That's the correct place to report this bug.

**Comment by weishanlee** [comment]
> @weishanlee can you please report it here: https://github.com/sympy/sympy? That's the correct place to report this bug.

Done it! Sorry about the delay!
