### ISSUE TITLE
Parentheses on the website are ill-formatted.

### ISSUE THREAD

**Issue by dynamicwebpaige** [sympy/sympy.github.com#163]
Tested using Microsoft Edge, on Windows 10; these parentheses seem to be a little too into self-expression. 😊

**Reference**: 
https://docs.sympy.org/latest/tutorial/calculus.html

**Screenshot**:
![image](https://user-images.githubusercontent.com/3712347/138639866-2f17429e-0555-4ec5-809c-2b946831b71e.png)

**Comment by oscarbenjamin** [comment]
I just checked from firefox and the brackets all look fine. I think this is a problem with edge and possibly its support for unicode fonts.

**Comment by sumit-158** [comment]
@dynamicwebpaige can I work on this?

**Comment by asmeurer** [comment]
Unfortunately the unicode pretty printing characters won't look good unless you have the right fonts. See https://github.com/sympy/sympy/issues/15700. For now, we should maybe consider removing the Unicode pretty printing from the tutorial.
