### ISSUE TITLE
Numerical evaluation of binomial from mpmath seems to be based on the other definition so SymPy's exact and numeric evaluation of binomials is currently inconsistent:

### ISSUE THREAD

**Issue by MyTrueWallet** [sympy/sympy.github.com#182]
Numerical evaluation of binomial from mpmath seems to be based on the other definition so SymPy's exact and numeric evaluation of binomials is currently inconsistent:
```python
In [8]: b = binomial(-1, -1, evaluate=False)

In [9]: b
Out[9]: 
⎛-1⎞
⎜  ⎟
⎝-1⎠

In [10]: b.doit()
Out[10]: 0

In [11]: b.evalf()
Out[11]: 1.00000000000000
```

_Originally posted by @oscarbenjamin in https://github.com/sympy/sympy/issues/14577#issuecomment-1127015051_

**Comment by MyTrueWallet** [comment]
g p

**Comment by ivanistheone** [comment]
Clickable link to see the issue: https://live.sympy.org/?evaluate=b%20%3D%20binomial(-1%2C%20-1%2C%20evaluate%3DFalse)%0Ab%0A%23--%0Ab.doit()%0A%23--%0Ab.evalf()%0A

**Comment by asmeurer** [comment]
Why did you open this issue in this repo? This is the website repo, and only issues with the website should be opened here. If anything, an issue for this should be opened in the mpmath repo, with a reference to the SymPy discussion.
