### ISSUE TITLE
Auto height of right sidebars.

### ISSUE THREAD

**Issue by goodok** [sympy/sympy.github.com#43]
Now right sidebars have foxed height.
But for localization versions, the text differ a littele, so the height must be tuned more or less.

E.g see.
http://s011.radikal.ru/i318/1201/ff/11b6ac9fb307.png

The top right sidebar has a big height.
The second right sidebar has small height.

**Comment by mvnnn** [comment]
@asmeurer this issue is open ?

**Comment by asmeurer** [comment]
I don't see it. If you do let me know and we can reopen this.
