### ISSUE TITLE
404 errors for Physics example notebooks

### ISSUE THREAD

**Issue by willingc** [sympy/sympy.github.com#77]
On http://sympy.org/en/features.html in two IPython notebook examples for Physics, the links redirect to a repo that has been moved or changed. For example, the first notebook links to http://nbviewer.ipython.org/github/PythonDynamics/pydy_examples/blob/master/tutorials/beginner.ipynb which causes a 404. Same with the second notebook example.

Unfortunately, https://github.com/PythonDynamics/ has private not public repos. 

The links in https://github.com/sympy/sympy.github.com/blob/master/en/features.html on lines 288 and 289 need to be updated to the location that the notebooks currently exist. Likely need to check the other language folders for features.html to see if the links need updating as well.

**Comment by argriffing** [comment]
The sympy webpage still links to a 404 PythonDynamics page

**Comment by asmeurer** [comment]
Can you be more specific where the link is? I don't see any links to PythonDynamics at sympy.org.

**Comment by argriffing** [comment]
https://github.com/sympy/sympy.github.com/blob/master/templates/features.html#L268

http://nbviewer.ipython.org/urls/raw2.github.com/PythonDynamics/pydy_examples/master/mass_spring_damper/mass_spring_damper.ipynb

**Comment by asmeurer** [comment]
https://github.com/sympy/sympy.github.com/compare/master...asmeurer:pydy-notebook?expand=1
