### ISSUE TITLE
sympy.org is failing dns

### ISSUE THREAD

**Issue by evelynmitchell** [sympy/sympy.github.com#84]
http://downorjustforme.com/sympy.org 2016-01-03 15:25 UTC +7 shows down.

**Comment by certik** [comment]
That link shows up for me. I check linode where our name servers are, it seems to be up and running. Last thing to check is if the domain sympy.org still redirects to linode. @asmeurer would you mind checking that?

**Comment by evelynmitchell** [comment]
This is a linode.com related problem. All 3 of the authoritative name servers are on linode. A free tertiary dns would be helpful.

**Comment by certik** [comment]
@evelynmitchell thanks. Do you know how to debug this? I.e. if it is some problem of my setup on linode, or if linode itself has some issues with the name servers?

**Comment by evelynmitchell** [comment]
Linode is having a big denial of service attack. (status.linode.com)  A 3rd dns for sympy.org, pointing to a non-linode, static site, would keep you up, while this is happening.

**Comment by asmeurer** [comment]
sympy.org works for me here. Perhaps going directly go sympy.github.io is a workaround?

**Comment by certik** [comment]
Thanks @evelynmitchell, so that explains it. Do you have any recommendation for a dns server that we could use?

**Comment by evelynmitchell** [comment]
http://www.zoneedit.com/free_dns.html looks like a good fit.
You want free tertiary dns. Linode will continue to be a good choice for primary and seconday.

**Comment by asmeurer** [comment]
@certik I believe this stuff is all handled by NumFOCUS now, so we'd need to get them to set this up.
